### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by dmitryr117** [Zenika/alpine-chrome#26]
Hi There. I am trying to set it up to use with docker-compose. However when I try to activate it the container keeps restarting and the terminal gives me:

[0511/154746.370034:WARNING:dns_config_service_posix.cc(335)] Failed to read DnsConfig.
docker-compose is as follows:

version: '3'
services:
  testservice
    build: ./installer
    container_name: testservice
    restart: always
    ports:
      - 9222:9222

**Comment by jlandure** [comment]
Hi @dmitryr117 👋 
Thanks for the feedback and opening an issue.

I didn't have a direct answer for your problem but I can investigate to help you.
Can you please add some details on the `docker-compose` ?

For your information, the log `Failed to read DnsConfig` is a warning from Chromium. Do you have a `ERROR` or `FATAL` in your logs?
You can print more logs using the command described here `--log-level=0`: https://github.com/Zenika/alpine-chrome/issues/15#issuecomment-423814438

**Comment by jlandure** [comment]
Hi @dmitryr117 
Any news on your issue?

**Comment by jlandure** [comment]
Hi @dmitryr117 👋 
Do you have any news to understand your issue?
Without any news, I will close the issue next week...

**Comment by likwid** [comment]
I am also having this problem, and I am willing to provide you with whatever details you need.

I removed docker-compose from the equation, and I receive this error just doing plain docker run.

`docker run -it --security-opt seccomp=$(pwd)/chrome.json zenika/alpine-chrome:73` exits immediately with return code of 0, and the only thing that shows up in the logs is `[0529/204426.581579:WARNING:dns_config_service_posix.cc(335)] Failed to read DnsConfig.
 ubuntu`

I have tried a number of combinations, such as previous versions of alpine-chrome, removing the security-opt settings, and overriding entrypoint with shell, so that I can run the entrypoint directly myself.

The behavior I expect is that chrome stays running in the foreground, but that doesn't seem to be happening. As far as I can tell adding `--log-level=0` does nothing.  

```bash
docker run -it --entrypoint sh zenika/alpine-chrome:73
/usr/src/app $ chromium-browser --headless --log-level=0 --disable-gpu --disable-software-rasterizer --no-sandbox
[0529/205209.922919:WARNING:dns_config_service_posix.cc(335)] Failed to read DnsConfig.
/usr/src/app $
```

**Comment by jlandure** [comment]
Hi @likwid 👋 
Thanks for your feedbacks!

For your information, the log `Failed to read DnsConfig` is a **warning** from Chromium (not an error or a fatal problem). 👍 

I don't really understand the expected behavior you're waiting for. 😅 

I explained myself:
- you launch your container: `docker run -it --entrypoint sh zenika/alpine-chrome:73`
- you launch Chromium without action or website to visit, just flags `chromium-browser --headless --log-level=0 --disable-gpu --disable-software-rasterizer --no-sandbox`
- you get an quick exit from the headless Chromium process and you get a `0` return that matchs a successful command 👍 

Can you try adding an action to your headless chrome like the following ones?
- [printing the DOM](https://github.com/Zenika/alpine-chrome#print-the-dom)
- [printing a pdf](https://github.com/Zenika/alpine-chrome#print-a-pdf)
- [take a screenshot](https://github.com/Zenika/alpine-chrome#take-a-screenshot)

Reminder: the objective of this docker image is to provide a "Headless" Chrome (without any graphical user interface).
I found [this issue](https://github.com/karma-runner/karma-chrome-launcher/issues/160) on runnning headless Chrome in the background. Is that something you want to achieve? Can you explain your idea?

**Comment by likwid** [comment]
My bad 🥇 

What I thought would happen is that chrome would just continue to run in the foreground, but be accessible over a port. I see now in the documentation, that you are passing a URL.

Sorry, not sure how I missed that the first time.  

![I can show myself the door](https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif "I can show myself the door")

**Comment by jlandure** [comment]
Hi @likwid 👋 

No problem.
Do you think I need to explain more precisely how it works in the `README`? 🤔 
Can you describe the usecase you want to run with this image? perhaps to help others?

Thank you. BTW, lol for your homer gif 👍

**Comment by jlandure** [comment]
Hi @likwid 👋 

Without any news from you, I will close this issue next week.

**Comment by jlandure** [comment]
@all-contributors please add @likwid @dmitryr117 for bug
